version: '3.5'

services:
  app:
    image: ghcr.io/kotyra23/landing:latest
    networks:
      - internal
    deploy:
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend-nginx-http.rule=Host(`rbr.kis.im`)"
        - "traefik.http.routers.backend-nginx-http.entrypoints=http"
        - "traefik.http.routers.backend-nginx-http.middlewares=https-redirect"
        - "traefik.http.routers.backend-nginx-https.rule=Host(`rbr.kis.im`)"
        - "traefik.http.routers.backend-nginx-https.entrypoints=https"
        - "traefik.http.routers.backend-nginx-https.tls=true"
        - "traefik.http.routers.backend-nginx-https.tls.certresolver=le"
        - "traefik.http.routers.backend-nginx-https.service=backend-nginx-svc"
        - "traefik.http.services.backend-nginx-svc.loadbalancer.server.port=8090"

networks:
  internal:
    external: true
